-- World State Schema — Life Organizer
-- Migration: 20260518000000_create_world_state_schema
--
-- HOW TO RUN:
--   Paste this entire file into the Supabase SQL editor and click Run.
--   Or: supabase db push (if using the Supabase CLI with local dev setup).
--
-- IRREVOCABLE DECISIONS (do not alter without a new migration):
--   • All timestamps: timestamptz (never plain timestamp — loses timezone data)
--   • All JSON: jsonb (never json — jsonb supports indexing and is faster)
--   • Primary keys: bigint generated by default as identity (not UUID)
--   • Every table has user_id uuid referencing auth.users (RLS-ready from day 1)
--   • Every table has created_at + updated_at; updated_at is set by trigger
--   • RLS is enabled on every table
--
-- Tables created (8):
--   calendar_snapshot   Google Calendar events, snapshotted per day
--   open_tasks          Manual + intake-generated tasks
--   beads_ready         Cached snapshot of Beads Service ready issues
--   rules               Rules Engine rule definitions
--   notification_log    Record of every notification fired
--   recommendation_history  Context Reasoner outputs
--   rule_suggestions    Pattern Analyzer suggestions for rule changes
--   user_preferences    Per-user settings (one row per user)


-- ============================================================
-- EXTENSIONS
-- ============================================================

-- moddatetime: automatically updates the updated_at column on every UPDATE.
-- Must be enabled before the trigger function is created.
create extension if not exists moddatetime schema extensions;


-- ============================================================
-- HELPER: updated_at trigger
-- ============================================================
-- A single trigger function reused by all tables.
-- Usage: see "create trigger set_updated_at..." below each table.

create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ============================================================
-- TABLE: calendar_snapshot
-- ============================================================
-- One row per calendar day per user.
-- The Context Collector writes a fresh snapshot on each sync.
-- "events" is the full array of calendar events for that day.

create table if not exists public.calendar_snapshot (
  id              bigint      generated by default as identity primary key,
  user_id         uuid        not null references auth.users on delete cascade,
  event_date      date        not null,
  events          jsonb       not null default '[]',   -- [{id, title, start, end, location, attendees[], status}]
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  unique (user_id, event_date)
);

create index if not exists calendar_snapshot_user_date
  on public.calendar_snapshot (user_id, event_date desc);

create trigger set_updated_at
  before update on public.calendar_snapshot
  for each row execute procedure public.handle_updated_at();

alter table public.calendar_snapshot enable row level security;

create policy "Users can manage their own calendar snapshots"
  on public.calendar_snapshot
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ============================================================
-- TABLE: open_tasks
-- ============================================================
-- Manual tasks and tasks extracted by intake agents.
-- "time_required_minutes" feeds the open-block matching rule in the Rules Engine.

create table if not exists public.open_tasks (
  id                      bigint      generated by default as identity primary key,
  user_id                 uuid        not null references auth.users on delete cascade,
  title                   text        not null,
  status                  text        not null default 'pending',  -- pending | in_progress | completed | cancelled
  priority                smallint    not null default 2,           -- 0 (critical) – 4 (backlog), mirrors beads scale
  time_required_minutes   integer,                                  -- estimated effort; used by open-block matching rule
  deadline                timestamptz,
  completed_at            timestamptz,
  source                  text        not null default 'manual',   -- manual | email_intake | conversation_intake | rules_engine
  source_url              text,                                     -- deeplink back to origin (email ID, conversation ref, etc.)
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

create index if not exists open_tasks_user_status
  on public.open_tasks (user_id, status);

create index if not exists open_tasks_deadline
  on public.open_tasks (user_id, deadline)
  where deadline is not null;

create trigger set_updated_at
  before update on public.open_tasks
  for each row execute procedure public.handle_updated_at();

alter table public.open_tasks enable row level security;

create policy "Users can manage their own tasks"
  on public.open_tasks
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ============================================================
-- TABLE: beads_ready
-- ============================================================
-- Cached snapshot of "ready" Beads issues from the Beads Service.
-- The Context Collector writes this on each sync; the Rules Engine reads it.
-- Full Beads data lives in the Railway Beads Service — this is a read cache only.

create table if not exists public.beads_ready (
  id          bigint      generated by default as identity primary key,
  user_id     uuid        not null references auth.users on delete cascade,
  issue_id    text        not null,                -- e.g. "life-xqz"
  title       text        not null,
  priority    smallint,                            -- 0–4
  blocked_by  jsonb       not null default '[]',  -- [issue_id, ...] of open blockers
  synced_at   timestamptz not null default now(),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  unique (user_id, issue_id)
);

create index if not exists beads_ready_user_id
  on public.beads_ready (user_id);

create trigger set_updated_at
  before update on public.beads_ready
  for each row execute procedure public.handle_updated_at();

alter table public.beads_ready enable row level security;

create policy "Users can manage their own beads cache"
  on public.beads_ready
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ============================================================
-- TABLE: rules
-- ============================================================
-- Rules Engine rule definitions.
-- "condition_type" is a short enum-like key understood by the Rules Engine.
-- "condition_config" holds the rule-specific parameters.
-- "total_fires", "accepted_count", "dismissed_count" feed the Pattern Analyzer.

create table if not exists public.rules (
  id                  bigint      generated by default as identity primary key,
  user_id             uuid        not null references auth.users on delete cascade,
  name                text        not null,
  description         text,
  condition_type      text        not null,   -- e.g. 'open_block', 'deadline_proximity', 'issue_unblocked', 'task_stalled'
  condition_config    jsonb       not null,   -- rule-specific params: thresholds, durations, priorities
  priority_threshold  smallint    not null default 2,   -- minimum task priority to fire (0=always, 4=critical only)
  cooldown_minutes    integer     not null default 60,  -- minimum gap between firings for the same rule
  total_fires         integer     not null default 0,
  accepted_count      integer     not null default 0,   -- user clicked "do it" or similar
  dismissed_count     integer     not null default 0,   -- user dismissed without acting
  last_fired_at       timestamptz,
  deprecated_at       timestamptz,                      -- null = active; set by Pattern Analyzer to soft-delete
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists rules_user_active
  on public.rules (user_id)
  where deprecated_at is null;

create trigger set_updated_at
  before update on public.rules
  for each row execute procedure public.handle_updated_at();

alter table public.rules enable row level security;

create policy "Users can manage their own rules"
  on public.rules
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ============================================================
-- TABLE: notification_log
-- ============================================================
-- Every notification dispatched by the Notification Dispatcher.
-- "user_action" tracks whether the user acted, dismissed, or ignored.
-- "action_latency_seconds" feeds the Pattern Analyzer's acceptance timing analysis.

create table if not exists public.notification_log (
  id                      bigint      generated by default as identity primary key,
  user_id                 uuid        not null references auth.users on delete cascade,
  rule_id                 bigint      references public.rules on delete set null,
  channel                 text        not null,  -- push | email | in_app
  title                   text        not null,
  body                    text,
  payload                 jsonb,                 -- full context payload sent with notification
  fired_at                timestamptz not null default now(),
  user_action             text,                  -- accepted | dismissed | ignored | null (not yet seen)
  action_at               timestamptz,
  action_latency_seconds  integer,               -- computed from fired_at → action_at
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

create index if not exists notification_log_user_fired
  on public.notification_log (user_id, fired_at desc);

create index if not exists notification_log_rule_id
  on public.notification_log (rule_id)
  where rule_id is not null;

create trigger set_updated_at
  before update on public.notification_log
  for each row execute procedure public.handle_updated_at();

alter table public.notification_log enable row level security;

create policy "Users can manage their own notification log"
  on public.notification_log
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ============================================================
-- TABLE: recommendation_history
-- ============================================================
-- Outputs from the Context Reasoner (on-demand Claude call).
-- "content" is a jsonb array of recommendations, each with title/body/rationale/actions.
-- "world_state_snapshot" is a condensed snapshot of what was passed to Claude.

create table if not exists public.recommendation_history (
  id                      bigint      generated by default as identity primary key,
  user_id                 uuid        not null references auth.users on delete cascade,
  content                 jsonb       not null,  -- [{title, body, rationale, priority, actions[]}]
  world_state_snapshot    jsonb,                 -- condensed WS at time of call
  user_action             text,                  -- accepted | dismissed | partial | null
  model                   text,                  -- claude model used
  prompt_tokens           integer,
  completion_tokens       integer,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

create index if not exists recommendation_history_user
  on public.recommendation_history (user_id, created_at desc);

create trigger set_updated_at
  before update on public.recommendation_history
  for each row execute procedure public.handle_updated_at();

alter table public.recommendation_history enable row level security;

create policy "Users can manage their own recommendations"
  on public.recommendation_history
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ============================================================
-- TABLE: rule_suggestions
-- ============================================================
-- Pattern Analyzer suggestions for rule changes.
-- "approved" is a tri-state: null = pending review, true = applied, false = rejected.
-- "applied_at" is set when the suggestion is actually executed, not just approved.

create table if not exists public.rule_suggestions (
  id              bigint      generated by default as identity primary key,
  user_id         uuid        not null references auth.users on delete cascade,
  suggestion_type text        not null,   -- threshold_adjustment | cooldown_adjustment | new_rule | deprecate
  target_rule_id  bigint      references public.rules on delete set null,
  original_value  jsonb,                  -- current value of the field being changed
  suggested_value jsonb       not null,   -- the proposed new value
  reasoning       text        not null,   -- Pattern Analyzer's explanation
  confidence      real        not null,   -- 0.0–1.0
  approved        boolean,               -- null=pending, true=apply, false=reject
  approved_at     timestamptz,
  applied_at      timestamptz,           -- when the change was actually made
  model           text,
  analysis_date   date        not null default current_date,
  created_at      timestamptz not null default now()
);

-- No updated_at on this table — suggestions are append-only;
-- approvals update the approved/applied fields rather than rows.

create index if not exists rule_suggestions_user_pending
  on public.rule_suggestions (user_id, created_at desc)
  where approved is null;

alter table public.rule_suggestions enable row level security;

create policy "Users can manage their own rule suggestions"
  on public.rule_suggestions
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ============================================================
-- TABLE: user_preferences
-- ============================================================
-- One row per user. Insert a default row on user sign-up (via Supabase trigger or app).

create table if not exists public.user_preferences (
  id                          bigint      generated by default as identity primary key,
  user_id                     uuid        not null references auth.users on delete cascade unique,
  notifications_enabled       boolean     not null default true,
  quiet_hours_start           time,                    -- e.g. 22:00 (null = no quiet hours)
  quiet_hours_end             time,                    -- e.g. 07:00
  email                       text,                    -- notification email (may differ from auth email)
  timezone                    text        not null default 'America/Toronto',
  auto_apply_threshold        real        not null default 0.85,  -- Pattern Analyzer auto-apply confidence threshold
  updated_at                  timestamptz not null default now()
  -- No created_at: use auth.users.created_at for the user's join date
);

create trigger set_updated_at
  before update on public.user_preferences
  for each row execute procedure public.handle_updated_at();

alter table public.user_preferences enable row level security;

create policy "Users can manage their own preferences"
  on public.user_preferences
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
