-- Migration C: Create category_weights, block_rejections, checkin_log
-- Phase 1 intelligence layer — life-xny

-- ── category_weights ──────────────────────────────────────────────────────────
-- User-defined and Pattern Analyzer-learned priority per category.
-- No CHECK constraint on category — categories are dynamic (user-configurable).
-- Seeded by recommend.js on first run (5 rows at weight=0.5 per default category).
create table if not exists public.category_weights (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null references auth.users on delete cascade,
  category       text not null,
  weight         real not null default 0.5,  -- 0.0 (suppress) to 1.0 (always surface)
  rationale      text,
  set_by         text not null default 'user',  -- 'user' | 'pattern_analyzer'
  effective_from timestamptz not null default now(),
  expires_at     timestamptz,
  created_at     timestamptz not null default now()
);
create index if not exists category_weights_user_category_time
  on public.category_weights (user_id, category, effective_from desc);

-- ── block_rejections ──────────────────────────────────────────────────────────
-- "Keep this time block free" signals.
-- released_at = null  → active rejection (excluded from free block computation)
-- released_at = <ts>  → user released the block (treated as available again)
-- Pattern Analyzer counts active rejections to suggest permanent protected blocks.
create table if not exists public.block_rejections (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users on delete cascade,
  rejected_at  timestamptz not null default now(),
  day_of_week  smallint not null check (day_of_week between 0 and 6),
  start_time   time not null,
  end_time     time not null,
  source       text not null default 'user',  -- 'user' | 'implicit'
  released_at  timestamptz
);
create index if not exists block_rejections_user_day
  on public.block_rejections (user_id, day_of_week)
  where released_at is null;

-- ── checkin_log ───────────────────────────────────────────────────────────────
-- Periodic collaborative questions and answers (Phase 3 populates).
-- Table created now so schema is stable; no code writes to it until Phase 3.
create table if not exists public.checkin_log (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users on delete cascade,
  trigger_type  text not null,   -- 'scheduled' | 'event'
  trigger_event text,            -- e.g. 'category_inactive:hobby'
  questions     jsonb not null,  -- [{ id, text, type: 'priority'|'balance'|'deadline' }]
  answers       jsonb,           -- [{ question_id, answer_text, answered_at }]
  model         text,
  generated_at  timestamptz not null default now(),
  answered_at   timestamptz,
  created_at    timestamptz not null default now()
);
